version: '2'

services:
    memcached:
        image: memcached
        container_name: memcached
        ports:
            - "11211:11211"
    redis:
        image: 'redis:alpine'
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - './etc/redis.conf:/etc/redis.conf'
    mysql:
        image: mysql
        container_name: mysql
        volumes:
            - ./var/mysql/data:/mysql_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
    php:
        build: ./images/php
        container_name: php
        volumes:
            - ./etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf   
            - ~/webroot/test:/var/www/html
        links:
            - memcached
            - mysql
        restart: always

    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./var/nginx/log:/var/log/nginx
            - ~/webroot/test:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        restart: always
